### ISSUE TITLE
Small question about `closest()` polyfill

### ISSUE THREAD

**Issue by lvmajor** [geoffreycrofte/form-saver#2]
Hey there, just wondering why you have a `closest` polyfill when the rest of the code is not using it? 

Is there future/past purpose to this polyfill being there? 

thanks in advance! :)

**Comment by geoffreycrofte** [comment]
Hello @os1r1s110 
Sorry for the delay, I didn't receive notification.
You are right, the `closest()` polyfill is totally useless for the moment. I planned to create some other option taht would use it, but I didn't do it yet :)

You can remove it if you use the script as it is.
Thank you for your question ;p
